//
// Created by Danil on 17.08.2023.
//

#ifndef LEGACYRUNTIME_ARCHITECTURALDEFINES_H
#define LEGACYRUNTIME_ARCHITECTURALDEFINES_H


enum TypeT {
    PRIMITIVE_WSTRING = 0,
    PRIMITIVE_INTEGER = 1,
    OBJECT_WITH_FIELDS = 2
};

#endif //LEGACYRUNTIME_ARCHITECTURALDEFINES_H
