//
// Created by Danil on 15.08.2023.
//

#ifndef LEGACYRUNTIME_ARCHITECTURALDEFINES_H
#define LEGACYRUNTIME_ARCHITECTURALDEFINES_H

enum ILTokenTypes {
    TASSEMBLY = 0,
    TMODULE = 1,
    TNAMESPACE = 2,
    TCLASS = 3,
    TMETHOD = 4,
    TINSTRUCTION = 5
};

enum ILUtility {
    INSTRUCTION_NAME_END = '.',
    INSTRUCTION_END = ';'
};


#endif //LEGACYRUNTIME_ARCHITECTURALDEFINES_H
