//
// Created by Danil on 15.08.2023.
//

#ifndef LEGACYRUNTIME_ARCHITECTURALDEFINES_H
#define LEGACYRUNTIME_ARCHITECTURALDEFINES_H

enum ILTokenTypes {
    ASSEMBLY = 0,
    MODULE = 1,
    NAMESPACE = 2,
    CLASS = 3,
    METHOD = 4,
    INSTRUCTION = 5
};

enum ILUtility {
    INSTRUCTION_NAME_END = '.',
    INSTRUCTION_END = ';'
};


#endif //LEGACYRUNTIME_ARCHITECTURALDEFINES_H
